[package]
name = "tinyparse_macro"
version = "1.2.3-alpha"
edition = "2021"
description = "Macros for tinyparse"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0.39"
